### ISSUE TITLE
tab-complete friends

### ISSUE THREAD

**Issue by marwahaha** [marwahaha/friendlog#31]
that way, I don't have to type the whole name

**Comment by prendradjaja** [comment]
Yeah, I'm super into this idea. I think #23 helps a little bit, but tab-complete would be clutch.

(For completeness: I think tab-complete should only operate on full names, not nicknames/aliases or partial names)

I'll probably work on this soon, just because I particularly want it to exist. :) Self-assigning, but as with everything else feel free to swoop it from me if I'm taking a while. (I'm particularly busy at work this week, so probably everything I've assigned myself will take a while, haha)
