### ISSUE TITLE
Fails if data files don't exist

### ISSUE THREAD

**Issue by annapapitto** [marwahaha/friendlog#45]
For new users, data/friends.json and data/events.json don't exist yet. Running a `friendlog add` errors out:
```
fs.js:667
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '/Users/anna/friendlog/data/friends.json'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at loadFriendsData (/Users/anna/friendlog/index.js:22:23)
    at addFriend (/Users/anna/friendlog/index.js:95:17)
    at main (/Users/anna/friendlog/index.js:226:5)
    at Object.<anonymous> (/Users/anna/friendlog/index.js:244:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
```

There are a couple options:
1. Add creation of these files to the Readme Setup steps. (cons: probably easy to automate, would have to maintain the list of files)
2. Add creation to the npm install process (not sure if this is possible, but it seems reasonably likely)
3. Write a setup script that creates the files (and could also add the necessary alias to their bash profile)
4. Probably other options.

**Comment by prendradjaja** [comment]
Hi Anna! I like your thoroughness. For smallish things like this definitely feel free to use your judgment (i.e. choose which approach is best) and make a PR instead of an issue (though of course it doesn't hurt to discuss, and for bigger things discussion is definitely best).

I'm totally fine with any of these options.

Here's another option: (which is probably overengineering, though -- and at some point we'll probably migrate to a real database or something, so not worth the effort to do anything other than the easiest solution to solve this problem of JSON files)

5. If the file doesn't exist, create it. (if it doesn't exist upon reading, pretend it's `[]`; if it doesn't exist upon writing, create it with contents `[]`)

**Comment by marwahaha** [comment]
I have a hack already -- when you're in the repository, use `npm run reset` and the files will be created.
